TARGETS = sascore adsrcurve getheight keyon keyoff noise outputmode pcm pitch setadsr vag pause
EXTRA_LIBS = -lpspaudio
EXTRA_OBJS = sascore-imports.o

COMMON_DIR = ../../../common
include $(COMMON_DIR)/common.mk
