TARGETS = scheduling dispatch costs delaylen preemptsyscall syscallkinds callcosts delayzero handoff readyqueue preemptuser waittimeouts alarmcosts dispatchwake mutexhandoff
EXTRA_OBJS = lwmutex-imports.o ../../audio/atrac/atrac-imports.o
EXTRA_LIBS = -lpsputility

COMMON_DIR = ../../../common
include $(COMMON_DIR)/common.mk
