TARGETS = scheduling dispatch costs delaylen preemptsyscall syscallkinds
EXTRA_OBJS = lwmutex-imports.o ../../audio/atrac/atrac-imports.o
EXTRA_LIBS = -lpsputility

COMMON_DIR = ../../../common
include $(COMMON_DIR)/common.mk
