TARGETS = linear mipmaplinear nearest precisionlinear2d precisionlinear3d precisionnearest2d precisionnearest3d
EXTRA_OBJS = ../../dmac/dmac-imports.o shared.o
EXTRA_LIBS = -lpspgum -lm -lstdc++ -lc

COMMON_DIR = ../../../common
include ../../../common/common.mk
