TARGETS = vector matrix prefixes colors convert gum vavg vregs convert_scaled callout minmax minmax_zero minmax_tie prefix_consume prefix_branch prefix_ctrl prefix_sat prefix_unpack
EXTRA_OBJS = colors_asm.S convert_asm.S callout_asm.S minmax_asm.S vfpu_common.c
LIBS = -lGLUT -lGL -lpspvfpu -lpspgu -lpsprtc -lpspgum -lpspmath -lcommon -lc -lm

COMMON_DIR = ../../../common
include $(COMMON_DIR)/common.mk
