TARGETS = mp3test initresource reserve release infotoadd notifyadd checkneeded
EXTRA_OBJS = mp3-imports.o
EXTRA_LIBS = -lpspaudio -lpspmp3 -lstdc++ -lc

COMMON_DIR = ../../../common
include $(COMMON_DIR)/common.mk
