TARGETS = basic \
	create setpsmf setpsmfoffset settempbuf start \
	getaudiodata getvideodata update \
	configplayer playmode selectspecific selectstream \
	getcurrentpts getcurrentstatus getcurrentstream getpsmfinfo
EXTRA_OBJS = psmf-imports.o mpeg-imports.o shared.o

COMMON_DIR = ../../../common
include $(COMMON_DIR)/common.mk
