TARGETS = basic \
	create setpsmf setpsmfoffset settempbuf \
	configplayer getcurrentstream getpsmfinfo selectspecific selectstream
EXTRA_OBJS = psmf-imports.o mpeg-imports.o shared.o

COMMON_DIR = ../../../common
include $(COMMON_DIR)/common.mk
