TARGETS = afterwait callbacks cancel check count create delete delivery exit nested notify refer
EXTRA_OBJS = ../mutex/mutex-imports.o ../../modules/loadexec-imports.o
EXTRA_LIBS = -lpsppower -lpspumd

COMMON_DIR = ../../../common
include $(COMMON_DIR)/common.mk
