TARGETS = afterwait callbacks cancel cbtimeout check count create delete delivery exit intrnotify nested notify otherthread recursion refer waittypes
EXTRA_OBJS = ../mutex/mutex-imports.o ../../modules/loadexec-imports.o
EXTRA_LIBS = -lpsppower -lpspumd

COMMON_DIR = ../../../common
include $(COMMON_DIR)/common.mk
