TARGETS = count planes vertexaddr viewport
EXTRA_OBJS = ../../dmac/dmac-imports.o shared.o
EXTRA_LIBS = -lpsppower -lpspgum -lm -lstdc++ -lc

COMMON_DIR = ../../../common
include ../../../common/common.mk
