TARGETS = basic blend blend565 blocktransfer cull material light
EXTRA_OBJS = ../../dmac/dmac-imports.o shared.o
EXTRA_LIBS = -lpspgum -lm -lstdc++ -lc

COMMON_DIR = ../../../common
include ../../../common/common.mk
