TARGETS = autosave filelist getsize idlist makedata sizes secureversion loaddata deletedata loademptyfilename deleteemptyfilename saveemptyfilename loadbroken deletebroken
EXTRA_OBJS = shared.o emptyfilename.o broken.o

COMMON_DIR = ../../../common
include $(COMMON_DIR)/common.mk
