TARGETS = transform planes coverage lines texture lighting curves nearclip pixel
EXTRA_OBJS = ../../dmac/dmac-imports.o shared.o jobs.o
EXTRA_LIBS = -lpspgum -lm -lstdc++ -lc

COMMON_DIR = ../../../common
include ../../../common/common.mk
