TARGETS = dither
EXTRA_OBJS = ../../dmac/dmac-imports.o ../commands/shared.o
EXTRA_LIBS = -lpspgum -lm -lstdc++ -lc
CFLAGS = -g -G0 -Wall -O0 -fno-strict-aliasing -std=gnu++0x

COMMON_DIR = ../../../common
include ../../../common/common.mk
