TARGETS = fonttest \
	charglyphimage charglyphimageclip find newlib open openfile openmem optimum \
	shadowglyphimage shadowglyphimageclip
EXTRA_OBJS = libfont-imports.o

COMMON_DIR = ../../common
include $(COMMON_DIR)/common.mk
