TARGETS = fonttest \
	altcharcode find newlib open openfile openmem optimum resolution \
	charglyphimage charglyphimageclip charimagerect \
	shadowglyphimage shadowglyphimageclip shadowimagerect
EXTRA_OBJS = libfont-imports.o

COMMON_DIR = ../../common
include $(COMMON_DIR)/common.mk
