TARGETS = fonttest \
	altcharcode charglyphimage charglyphimageclip find newlib open openfile openmem optimum \
	resolution shadowglyphimage shadowglyphimageclip
EXTRA_OBJS = libfont-imports.o

COMMON_DIR = ../../common
include $(COMMON_DIR)/common.mk
