TARGETS = continue lines linestrip indices points rectangles trianglefan triangles trianglestrip
EXTRA_OBJS = ../../dmac/dmac-imports.o shared.o
EXTRA_LIBS = -lpspgum -lm

COMMON_DIR = ../../../common
include ../../../common/common.mk
