TARGETS = threads create change extend exitstatus profiler threadend release rotate refer stackfree start suspend terminate termsuspended threadmanidlist threadmanidtype
EXTRA_OBJS = thread-imports.o

COMMON_DIR = ../../../common
include ../../../common/common.mk
